name: autotools make

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        brew install autoconf automake libtool
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure || cat config.log
    - name: make
      run: make -j $(nproc)
    - name: make check
      run: make check -j $(nproc)
    - name: make distcheck
      run: make distcheck -j $(nproc)
