name: autotools cross-compile make ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - arm-linux-gnueabihf
          - arm-linux-gnueabi
          - aarch64-linux-gnu
          - powerpc-linux-gnu
          - riscv64-linux-gnu
          - s390x-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        sudo apt update
        sudo apt install gcc-${{ matrix.host }} g++-${{ matrix.host }}
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure --host=${{ matrix.host }} --enable-static --disable-shared --without-zlib || cat config.log
    - name: make
      run: make -j $(nproc)
    - name: make check
      run: make check -j $(nproc)
